// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_WAzYe8o8EVv4p1LtjGS8Njq2m2JHQ7A',
    appId: '1:150295593311:web:7f445fddb3661c7870b6ea',
    messagingSenderId: '150295593311',
    projectId: 'cookbook1-ae381',
    authDomain: 'cookbook1-ae381.firebaseapp.com',
    storageBucket: 'cookbook1-ae381.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEsnwRAa8aXzeGBoNfLbYKqW_P6wrb1tI',
    appId: '1:150295593311:android:4e551d7ba5df2f4a70b6ea',
    messagingSenderId: '150295593311',
    projectId: 'cookbook1-ae381',
    storageBucket: 'cookbook1-ae381.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLElc1_-XClekcnfgeedX7Y5V1m7j-8Vk',
    appId: '1:150295593311:ios:f548d508cc5d8f7b70b6ea',
    messagingSenderId: '150295593311',
    projectId: 'cookbook1-ae381',
    storageBucket: 'cookbook1-ae381.appspot.com',
    iosBundleId: 'com.example.cookbookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLElc1_-XClekcnfgeedX7Y5V1m7j-8Vk',
    appId: '1:150295593311:ios:df66908278d93cf470b6ea',
    messagingSenderId: '150295593311',
    projectId: 'cookbook1-ae381',
    storageBucket: 'cookbook1-ae381.appspot.com',
    iosBundleId: 'com.example.cookbookApp.RunnerTests',
  );
}
